//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElasticSearch.ElasticLoader {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ElasticLoaderSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ElasticLoaderSettings defaultInstance = ((ElasticLoaderSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ElasticLoaderSettings())));
        
        public static ElasticLoaderSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CompanyDocumentReaderSettings {
            get {
                return ((string)(this["CompanyDocumentReaderSettings"]));
            }
            set {
                this["CompanyDocumentReaderSettings"] = value;
            }
        }
    }
}
